name: CI

on:
  push:
    branches: [ main ]
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v2

      - name: Generate olympusnews/index.txt
        run: |
          pushd olympusnews
          rm -f index.txt
          for f in *; do
            echo $f >> index.txt
          done
          popd

      - name: GitHub push to gh-pages
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.PUSH_TOKEN }}
          branch: gh-pages
          force: true
